sudo: required
dist: "xenial"
language: python
python:
 - "2.7"
virtualenv:
 system_site_packages: true
branches:
 only:
 - develop
 - master
before_install:
 - sudo apt-get -qq update
 # - sudo apt-get upgrade -y
 - sudo apt-get install -y root-system git python-pip libroot-bindings-python* libroot-roofit*
 - sudo -E -H pip install -U pip
 - sudo -E -H pip install -U https://github.com/yandex/rep/archive/stratifiedkfold.zip
 # - python -c 'import sys; print '\n'.join(sys.path)'


install:
 - "sudo -E -H pip install -U -r requirements.txt"
 - "python setup.py install --no-deps"
script:
 - pytest

deploy:
 provider: pypi
 user: mayou36
 password: woerter8PIP!
 distributions: "sdist bdist_wheel"
 on:
  branch: master


